version: '3'
services:
  api:
#    build: .
    image: todo:backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
#    volumes:
#      - .:/usr/src/app
  mongodb:
    image: mongo:latest